/**
 * Registro de ícones. Peso `fill` é o padrão da identidade — ícones sólidos,
 * com peso visual forte. Usa a variante SSR do Phosphor para poder aparecer
 * tanto em Server quanto em Client Components.
 */
import {
  Archive,
  ArrowBendUpLeft,
  ArrowClockwise,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bank,
  Barcode,
  Bell,
  CalendarBlank,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartLineUp,
  ChartPieSlice,
  ChatCircleDots,
  Check,
  CheckCircle,
  Clock,
  Copy,
  CreditCard,
  Cube,
  DownloadSimple,
  CurrencyDollar,
  DotsThreeOutline,
  Eye,
  EyeSlash,
  Key,
  LockKey,
  FileText,
  FunnelSimple,
  Gear,
  HandCoins,
  Handshake,
  House,
  Image as ImageIcon,
  Info,
  Lightning,
  ListChecks,
  MagnifyingGlass,
  MapPin,
  MegaphoneSimple,
  Medal,
  Minus,
  Moon,
  Package,
  Paperclip,
  PencilSimple,
  Percent,
  Phone,
  Plus,
  Prohibit,
  Receipt,
  ShieldCheck,
  SignOut,
  Shuffle,
  Sparkle,
  Storefront,
  Tag,
  Sun,
  Target,
  Trash,
  TrendUp,
  Trophy,
  Truck,
  TrayArrowUp,
  UploadSimple,
  User,
  UserCircle,
  UsersThree,
  WarningCircle,
  WhatsappLogo,
  X,
} from "@phosphor-icons/react/ssr";
import type { Icon as PhosphorIcon } from "@phosphor-icons/react";

export const ICONES = {
  // navegação
  dashboard: House,
  operacao: Package,
  financeiro: CurrencyDollar,
  marketing: MegaphoneSimple,
  equipe: UsersThree,
  configuracoes: Gear,
  minhaArea: UserCircle,
  pedidos: Package,
  autorizar: ShieldCheck,
  rastreio: Truck,
  cobranca: HandCoins,
  relatorio: ChartPieSlice,
  fornecedor: Handshake,
  comissoes: Receipt,
  metaAds: ChartLineUp,
  criativos: ImageIcon,
  colaboradores: UsersThree,
  ranking: Trophy,
  produtos: Cube,
  bancos: Bank,
  metas: Target,
  aparencia: Sparkle,

  // ações e adornos
  busca: MagnifyingGlass,
  notificacoes: Bell,
  filtros: FunnelSimple,
  adicionar: Plus,
  remover: Minus,
  fechar: X,
  voltar: CaretLeft,
  avancar: CaretRight,
  abrir: CaretDown,
  recolher: CaretUp,
  menu: DotsThreeOutline,
  expandir: ArrowRight,
  anterior: ArrowLeft,
  check: Check,
  checkCircle: CheckCircle,
  alerta: WarningCircle,
  info: Info,
  proibido: Prohibit,
  editar: PencilSimple,
  excluir: Trash,
  ver: Eye,
  ocultar: EyeSlash,
  cadeado: LockKey,
  chave: Key,
  escudo: ShieldCheck,
  copiar: Copy,
  upload: UploadSimple,
  anexo: Paperclip,
  atualizar: ArrowClockwise,
  arquivar: Archive,
  desarquivar: TrayArrowUp,
  exportar: UploadSimple,
  importar: DownloadSimple,
  transferencia: Shuffle,
  etiqueta: Tag,
  sair: SignOut,
  devolver: ArrowBendUpLeft,

  // domínio
  relogio: Clock,
  calendario: CalendarBlank,
  local: MapPin,
  telefone: Phone,
  whatsapp: WhatsappLogo,
  conversa: ChatCircleDots,
  codigo: Barcode,
  dinheiro: HandCoins,
  cartao: CreditCard,
  pix: Lightning,
  documento: FileText,
  loja: Storefront,
  percentual: Percent,
  medalha: Medal,
  lista: ListChecks,
  subiu: ArrowUp,
  desceu: ArrowDown,
  tendencia: TrendUp,
  usuario: User,
  sol: Sun,
  lua: Moon,
} satisfies Record<string, PhosphorIcon>;

export type NomeIcone = keyof typeof ICONES;
export type { PhosphorIcon };

export interface IconeProps {
  nome: NomeIcone;
  size?: number;
  weight?: "thin" | "light" | "regular" | "bold" | "fill" | "duotone";
  className?: string;
}

export function Icone({ nome, size = 18, weight = "fill", className }: IconeProps) {
  const Componente = ICONES[nome];
  return <Componente size={size} weight={weight} className={className} />;
}
